name       : pilot-link
version    : 0.12.5
release    : 1
source     :
    - http://downloads.pilot-link.org/pilot-link-0.12.5.tar.bz2 : d3f99ec04016b38995fb370265200254710318105c792c017d3aaccfb97a84b2
license    :
    - GPL-2.0
    - LGPL-2.0
summary    : pilot-link for Palm/PalmOS devices.
description: |
    pilot-link is a suite of tools used to connect your Palm or PalmOS® compatible handheld with Unix, Linux, and any other POSIX-compatible machine. pilot-link works with all PalmOS® handhelds, including those made by Handspring, Sony, and Palm, as well as others.
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libpng)
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --enable-libusb \
               --with-libiconv \
               --with-libpng \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove random empty dir
    rm -r %installroot%/usr/bin